build:
	go build -o my-module-app

run: build
	./my-module-app

# This way will make the output unseen in console, only the result from app content will show.
# build:
# 	@go build -o my-module-app

# run: build
# 	@./my-module-app